### ISSUE TITLE
Reverse proxy for service metadata documents

### ISSUE THREAD

**Issue by lucenasj** [sitmun/sitmun-backend-core#112]
We need to go through a proxy for the getcapabilites requests of the services in the administrator,
this is because the services do not have "access-control-allow-origin" in the header response

**Comment by fjlopez** [comment]
@codinachssm some services such as https://www.ign.es/wms-inspire/ign-base?request=GetCapabilities&service=WMS have  the header `access-control-allow-origin` in the response. So, I suggest to test functionalities https://github.com/sitmun/sitmun-admin-app/issues/49 and https://github.com/sitmun/sitmun-admin-app/issues/18 with such service (I can search additional services if requested) meanwhile we develop a solution for services that do not have such header.

Today, if a WMS service request does not respond with the header `access-control-allow-origin` or this header has a value different from `*` and does not include the host where SITMUN is available, it is possible that the service publisher do not want that a third party (e.g. SITMUN) uses such service in map viewers. If this was not the purpose of the service publisher, then it is a problem of the configuration of such service. 

Hence, this is not a bug, it is an enhancement as we are going to bypass this restriction imposed by the service publisher.

**Comment by codinachssm** [comment]
It works fine with the service https://www.ign.es/wms-inspire/ign-base

**Comment by fjlopez** [comment]
@lucenasj I just added a new endpoint to the API that follows the pattern `/api/helpers/capabilities?url={0}` where the {0} is replaced by the URI to a capabilities document. The endpoint returns 200 if the capabilities is retrieved and 400 otherwise. In both cases, the endpoint returns a JSON document with the following properties:

| property | type | description |
| ---------| ----- | ----- |
| `success` | boolean | `true` if the capabilities has been retrieved |
| `type`| string | if successful will contain `OGC:WMS` followed by the version number |
| `reason`| string | if failed will contain a text explaining the faliure |
| `asText`| string | the document returned by the endpoint; if successful it should contain an OGC capabilities document in XML |
| `asJson`| JSON object | if successful it should contain a JSON version of the the OGC capabilities document to ease the process by clients |
