### ISSUE TITLE
Field "values" in STM_FIL_GI table

### ISSUE THREAD

**Issue by gon-nexus** [sitmun/sitmun-backend-core#75]
When the backend returns a territorial filter, it has these fields:

column: "column"
id: 4
name: "Prueba12"
required: false
type: "C"
valueType: "A"
values: null
_links: {self: {…}, cartographyFilter: {…}, cartography: {…}, territorialLevel: {…}}

Looking at the tables schema, that table has a "value" field, i don't know if this field is missing, if the "values" field has an incorrect name, or that field name is correct and i have to change it, can you take a look?

**Comment by fjlopez** [comment]
The name `values` is correct because the mapped column `FGI_VALUE` stores multivalued data. The mapping is defined at:
https://github.com/sitmun/sitmun-backend-core/blob/06d4dcc2f8870ced307d366eecf2dc8d22bdf8f6/src/main/java/org/sitmun/plugin/core/domain/CartographyFilter.java#L72-L77

The logic of the mapping is as follows:

| `FGI_VALUE` | `values` |
|---|---|
|`NULL`| `null` |
|empty or blank| `[]`|
|`value1`|`[ "value1" ]`|
|`value1,value2`|`[ "value1" , "value2" ]`|
