### ISSUE TITLE
Create remaining languages

### ISSUE THREAD

**Issue by gon-nexus** [sitmun/sitmun-backend-core#84]
Can we have the remaining languages? As did it with Spanish language, we need Catalan and English.

**Comment by fjlopez** [comment]
Add [IETF definitions](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) for:

- [ ] Aranese (oc-aranes)
- [ ] Catalan (ca)
- [ ] English (en)
- [ ] Spanish (es)

**Comment by fjlopez** [comment]
Added languages and translations of the names of the languages:

- `/api/languages` returns the shortnames (BCP 47 language tag) and names in English of the 4 languages
- `/api/languages?lang=ca` returns the shortnames (BP 47 language tag) and names in Catalan of the 4 languages

@lucenasj I think that makes sense to rename the property as `languageTag` rather than `shortname`, isn't?
